name: Angular-Build-Workflow

on:
  push:
    branches: [ main ]

jobs:
  angular-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.x
      - name: install dependency
        run: npm install
      - name: angular build
        run: npm run build
      
